#################
### AUTOSTART ###
#################

exec-once=hyprpaper
exec-once=waybar
exec-once=swaync
exec-once = hypridle
exec-once = gpu-screen-recorder -w screen -f 60 -a "default_output" -r 60 -k h264 -c mp4 -o ~/Videos/replays/
