-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local vars = require("vars")

--##################

--## KEYBINDINGS ###

--##################

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(vars.mainMod .. " + " .. "T", hl.dsp.exec_cmd(vars.terminal))

hl.bind(vars.mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(vars.mainMod .. " + " .. "M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"))

hl.bind(vars.mainMod .. " + " .. "E", hl.dsp.exec_cmd(vars.fileManager))

hl.bind(vars.mainMod .. " + " .. "B", hl.dsp.exec_cmd(vars.browser))

hl.bind(vars.mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(vars.mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(vars.mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

-- dwindle

hl.bind(vars.mainMod .. " + " .. "R", hl.dsp.exec_cmd("~/.config/waybar/scripts/launch.sh"))

hl.bind("CTRL + ALT" .. " + " .. "T", hl.dsp.exec_cmd("sniptext --capture-now"))

hl.bind("ALT" .. " + " .. "P", hl.dsp.exec_cmd("~/.config/hypr/save-replay.sh"))

-- bind = $mainMod, L, exec, hyprlock

hl.bind(vars.mainMod .. " + " .. "Escape", hl.dsp.exec_cmd("wlogout -b 2"))

hl.bind("ALT" .. " + " .. "Space", hl.dsp.exec_cmd("tofi-run --drun-launch=true | xargs hyprctl dispatch exec --"))

hl.bind(vars.mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- 1 for waybar

hl.bind(vars.mainMod .. " + " .. "S", hl.dsp.exec_cmd("spotify"))

hl.bind("ALT" .. " + " .. "T", hl.dsp.exec_cmd("Telegram"))

hl.bind("ALT" .. " + " .. "O", hl.dsp.exec_cmd("obsidian"))

-- Zooming

hl.bind("SUPER + mouse_up", function()
    hl.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1.0')")
end)

hl.bind("SUPER + mouse_down", function()
    hl.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq 'if .float - 1.0 < 1 then 1 else .float - 1.0 end')")
end)

hl.bind("Print", hl.dsp.exec_cmd("~/.config/hypr/hypr-screenshot"))

-- Move focus with mainMod + arrow keys

hl.bind(vars.mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(vars.mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(vars.mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(vars.mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(vars.mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(vars.mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(vars.mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(vars.mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(vars.mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(vars.mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(vars.mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(vars.mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(vars.mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(vars.mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(vars.mainMod .. " + SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll

--bind = $mainMod, mouse_down, workspace, e+1

--bind = $mainMod, mouse_up, workspace, e-1

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(vars.mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(vars.mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
