-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: preload = "~/.config/hypr/wallpaper.jpg"

hl.config({
    wallpaper = {
        path = "~/.config/hypr/wallpaper.jpg",
        fit_mode = "cover",
    },
})
-- NOTE: Section 'wallpaper' may be a plugin or custom section; verify the output

-- TODO: manual review: splash = false
