-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "1920x1080@60",
    position = "auto",
    scale    = "auto",
})

--monitor=,3840x2160@160,auto,1.5

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local browser = "firefox"

local terminal = "ghostty"

local fileManager = "nautilus"

local menu = "tofi -show drun"

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("WLR_NO_HARDWARE_CURSORS", 1)

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("WLR_DRM_NO_ATOMIC", 1)

hl.env("__GL_VRR_ALLOWED", 0)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 0)

hl.env("QT_SCALE_FACTOR", 1.25)

hl.env("GDK_SCALE", 1)

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrules that are useful

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule

hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

-- Import files

-- source = ~/.config/hypr/binds.conf -> requires manual conversion
-- local binds = require("binds")
-- TODO: convert ~/.config/hypr/binds.conf to .lua and use require()

-- source = ~/.config/hypr/autostart.conf -> requires manual conversion
-- local autostart = require("autostart")
-- TODO: convert ~/.config/hypr/autostart.conf to .lua and use require()

-- source = ~/.config/hypr/input.conf -> requires manual conversion
-- local input = require("input")
-- TODO: convert ~/.config/hypr/input.conf to .lua and use require()

-- source = ~/.config/hypr/look.conf -> requires manual conversion
-- local look = require("look")
-- TODO: convert ~/.config/hypr/look.conf to .lua and use require()

-- source = ~/.config/hypr/mocha.conf -> requires manual conversion
-- local mocha = require("mocha")
-- TODO: convert ~/.config/hypr/mocha.conf to .lua and use require()
