-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        before_sleep_cmd = "loginctl lock-session",
        after_sleep_cmd = "hyprctl dispatch dpms on",
    },
})

hl.config({
    listener = {
        timeout = 150,
        -- 2.5 mins - turn screen off
        on_timeout = "hyprctl dispatch dpms off",
        on_resume = "hyprctl dispatch dpms on",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 300,
        -- 5 mins (hyprlock)
        on_timeout = "hyprlock",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 600,
        -- 10 mins (suspend)
        on_timeout = "systemctl suspend",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 1200,
        -- 20 mins (shutdown)
        on_timeout = "systemctl poweroff",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
